### PR TITLE
Heatwave in the Netherlands

### PR DESCRIPTION
**Pull request by Pratichhya**
In this notebook, we want to showcase a tool for mapping heatwaves using Sentinel-3 products. For this, we focused on De Bilt in the Netherlands and used specific conditions proposed by the ["National Heatwave Plan"](https://www.rivm.nl/en/heat/national-heatwave-plan) in the Netherlands.

Here, we want to show an usecase using the Copernicus Data Space Ecosystem backend

### CODE REVIEW

**Comment by jdries** [comment]
it should be possible to run this at full extent of netherlands now, can you try that?

**Comment by jdries** [comment]
Still found an issue myself with cloud masking:
https://github.com/Open-EO/openeo-geopyspark-driver/issues/670
(we'll want to do that as well in this notebook)

**Comment by Pratichhya** [comment]
> Still found an issue myself with cloud masking: [Open-EO/openeo-geopyspark-driver#670](https://github.com/Open-EO/openeo-geopyspark-driver/issues/670) (we'll want to do that as well in this notebook)

Applied to the whole of the Netherlands and tested this Cloud masking section, too. Thank you for helpful suggestions.

**Comment by jdries** [comment]
@Pratichhya can you do an update here in line with latest sentinel-3 updates?
scaling and offset are no longer needed
band names have changed

**Comment by Pratichhya** [comment]
> @Pratichhya can you do an update here in line with latest sentinel-3 updates? scaling and offset are no longer needed band names have changed

Updated as suggested

**Comment by Pratichhya** [comment]
Sorry for too many commits. I assume now it should be final for review.

**Review by jdries — CHANGES_REQUESTED** [review]
Nice! 
- flags_in:confidence_in can now be confidence_in
- in main README: refer to Sentinel-3 in 'demonstrates' column, avoid LST acronym in description.  Just refer to 'Sentinel-3 temperature data' or something similar that a broad public would understand.
- in the method, you will get multiple observations per day, but I do not see compositing. I think we need an aggregate_temporal with a max reducer?
- you have job_options, but do not explain why they are there. A lot of the values are also just defaults. It's good to show this more advanced feature, but needs explanation.
- Can  you display or mention the credit cost of the run? We want to start doing this, to also provide info on the cost of these use cases.

**Comment by Pratichhya** [comment]
@VictorVerhaert

**Comment by Pratichhya** [comment]
> Nice!
> 
> * flags_in:confidence_in can now be confidence_in
> * in main README: refer to Sentinel-3 in 'demonstrates' column, avoid LST acronym in description.  Just refer to 'Sentinel-3 temperature data' or something similar that a broad public would understand.
> * in the method, you will get multiple observations per day, but I do not see compositing. I think we need an aggregate_temporal with a max reducer?
> * you have job_options, but do not explain why they are there. A lot of the values are also just defaults. It's good to show this more advanced feature, but needs explanation.
> * Can  you display or mention the credit cost of the run? We want to start doing this, to also provide info on the cost of these use cases.

updated

**Comment by jdries** [comment]
looks good to me!
At some point, we could look into how to add a nice background map to plots like this, giving a bit more context as to where the heatwave is situated.

**Comment by Pratichhya** [comment]
In that case, if it's fine to merge as a first version, could you please accept it?

**Pull request merged**
