### PR TITLE
Update BAP composite notebook

### PR DESCRIPTION
**Pull request by VincentVerelst**
Updated the BAP composite notebook to have pre-defined functions in a util_bap, which is in line with the way the regression test is set up. The underlying algorithm hasn't changed.

### CODE REVIEW

**Review by HansVRP — COMMENTED** [review]
Did you mean to add the netCDF?

**Comment by jdries** [comment]
Note that not all users may understand that the notebook depends on an extra python file, they might think that 'utils_bap' is really a library or something. Perhaps its good to state that more explicitly?

**Comment by HansVRP** [comment]
@VincentVerelst did you manage to find the time to add a sentence on this in the notebook? If so, we can merge.

**Comment by VincentVerelst** [comment]
@HansVRP , I've commited an extra clarification

**Review by HansVRP — APPROVED** [review]

**Pull request merged**
