### PR TITLE
best available pixel composite

### PR DESCRIPTION
**Pull request by jdries**
Best available pixel, which is a rank composite where score is calculated based upon multiple criteria.
Here I work on distance to cloud, and distance to center of interval.

### CODE REVIEW

**Comment by jdries** [comment]
Works now, but had to use a workaround for nested array_apply.
Related:
https://github.com/Open-EO/openeo-geopyspark-driver/issues/544
https://github.com/Open-EO/openeo-geotrellis-extensions/issues/221

**Comment by jdries** [comment]
@VincentVerelst  can you integrate the work that relies on predefined processes a bit more? 
Also for the apply_neighborhood that runs the udf for distance to cloud: I expect you need to define more 'overlap' because otherwise you will not 'see' clouds that are outside of the chunk.

The final thing we could try is computing distance to cloud based on apply_kernel, not sure if it will work, but perhaps we can try to approximate the udf based implementation? A pure predefined process implementation would be quite nice.

**Comment by VincentVerelst** [comment]
Now also the spatial_resolution has been put in a variable, so that the rank_mask and rgb_bands always have the same spatial_resolution.

**Comment by VincentVerelst** [comment]
@jdries , the fourth B01 component has been added to the full_udf approach.

**Review by VincentVerelst — APPROVED** [review]

**Pull request merged**
