### PR TITLE
get started notebook first version

### PR DESCRIPTION
**Pull request by Pratichhya**
In this PR, we want to include a notebook for beginners to get started who immediately land on this page. Furthermore, the notebook will also be available in the Terrascope jupyter environment. 

Though the backend shown here is cdse, if it is recommended to use Terrascope we can.

### CODE REVIEW

**Comment by Pratichhya** [comment]
Suggestion received:
Rename the folder as 1. Getting started to be sure that it is always at the top
Be specific to direct to Cubes & clouds

**Comment by Pratichhya** [comment]
@HansVRP a kind reminder

**Comment by HansVRP** [comment]
- I agree with victor that it would be good to reference in the openEO community examples read my to getting started; 
People who visit the community examples will currently still not know where to find the basic info.

Example:
Title: Getting Started:
Python: [Link]

- Within the python getting started notebook, I would not necessarily reference to R or Java for simplicity

-  Discussing the concept of 'load collection returning a processable cube' might cause some confusion as load collection does not have a return in itself.

- Now, when you mention filtering, it's important to clarify what specifically you're filtering. 

- Lastly, regarding NDVI (nd()), it seems like there might be a small typo there.

**Comment by Pratichhya** [comment]
> * I agree with victor that it would be good to reference in the openEO community examples read my to getting started;
>   People who visit the community examples will currently still not know where to find the basic info.

Updated the sentence in the Readme to a more descriptive one https://github.com/Open-EO/openeo-community-examples/tree/get_started/python

> * Within the python getting started notebook, I would not necessarily reference to R or Java for simplicity

Removed the R and js from the sentence

> * Discussing the concept of 'load collection returning a processable cube' might cause some confusion as load collection does not have a return in itself.

rephrased the sentence

> * Now, when you mention filtering, it's important to clarify what specifically you're filtering.

added description to it

> * Lastly, regarding NDVI (nd()), it seems like there might be a small typo there.

Yes my fault 😄 thank you for noticing

**Comment by Pratichhya** [comment]
@HansVRP Sorry for earlier, I'm not sure why it happened, but now it should be there.

**Review by HansVRP — APPROVED** [review]

**Pull request merged**
