### PR TITLE
add gfm notebook

### PR DESCRIPTION
**Pull request by ValentinaHutter**

### CODE REVIEW

**Comment by ValentinaHutter** [comment]
would like to add this notebook about flood monitoring over the Pakistan flood in 2022 - this is use case 11.
would appreciate a review/merge :)

**Comment by ValentinaHutter** [comment]
> Nice! Some quick pointers:
> 
> * remove/avoid references to 'UC11', as this is not a project specific repo, especially also notebook filename
> * use openEO collection GHS_BUILT_S2 to load ghs data. Is not easy for people to understand another data loading mechanism
> * given that you do all postprocessing with xarray, saving results immediately to netCDF might be more appropriate? Would at least result in code simplifications
> * for batch jobs, use 'execute_batch' where possible. This notebook is not about explaining batch jobs, so no need to have multiple lines of code just to retrieve a result.

Thank you for your feedback, I tried to add it accordingly:

* removed UC11 references and created a new title.
* I looked into the GHS_BUILT_S2, but as the flood happened in 2022, I wanted to make use of the 2020 GHSL, whereas openeo provides 2018 GHSL. I now tried to simplify the example by saving some of the data. I think, the openeo users, that want to use GFM data, are aware of the GHSL and how to download it - so, I hope that's fine now :) 
* I now saved some of the data to NetCDF, but it did not change anything in terms of simplicity. I now removed some of the unnecessary lines, though :D
* I tried execute_batch, but unfortunately could not use it, as the jobs produce multiple files. I tried running smaller areas as well, but my area of interest seems to be exactly over two tiles. Therefore, I kept start_job, but removed unnecessary lines there as well 👍 

From my side, the updates are done - I hope that's fine with you :)

**Comment by ValentinaHutter** [comment]
Does someone else want to review this as well? :) @Pratichhya @m-mohr

**Comment by Pratichhya** [comment]
Hi @ValentinaHutter , I don't have much feedback; it looks good to me. However, there seems to be some conflict with the Readme file.

Also, just a suggestion: it would be nice to have an introduction at the start of the notebook explaining what it's about. While the current introduction covers the use of GFM, how about adding a few lines about the notebook's context and concluding the output with a short description?

> I tried execute_batch, but unfortunately, I could not use it, as the jobs produce multiple files. 

I am not sure if you want multiple files or not. If you need, when using `execute_batch`, you can save it as NC, and that already includes this multiple output. If not, then maybe `reduce_dimension` could fit your requirement.

**Comment by ValentinaHutter** [comment]
> Hi @ValentinaHutter , I don't have much feedback; it looks good to me. However, there seems to be some conflict with the Readme file.
> 
> Also, just a suggestion: it would be nice to have an introduction at the start of the notebook explaining what it's about. While the current introduction covers the use of GFM, how about adding a few lines about the notebook's context and concluding the output with a short description?
> 
> > I tried execute_batch, but unfortunately, I could not use it, as the jobs produce multiple files.
> 
> I am not sure if you want multiple files or not. If you need, when using `execute_batch`, you can save it as NC, and that already includes this multiple output. If not, then maybe `reduce_dimension` could fit your requirement.

Thank you for the quick reply! I am working on it! 

For the `execute_batch`, the reason why there are multiple files (in netcdf as well as in geotiff), is because the `spatial_extent`, I am interested in, is exactly above the borders of two individual tiles. So, while I do use `reduce_dimension` over the time dimension, I still produce two different tiles, with the same time step.

**Review by jdries — APPROVED** [review]

**Pull request merged**
