### PR TITLE
 Lowess Regression in openEO

### PR DESCRIPTION
**Pull request by Pratichhya**
This notebook attempts to mitigate these gaps in our time series data using a regression technique, specifically the Lowess model.
In this context, we implement Lowess smoothing directly within the openEO User-Defined Function (UDF). Given the objective of showcasing the integration of such models into the openEO workflow, this notebook mainly focuses on presentation rather than model finetuning.

### CODE REVIEW

**Comment by jdries** [comment]
there's a triple for loop in the udf, in python that is often a performance issue, was that checked?
xarray apply_ufunc might be an alternative, that's what we use a lot for timeseries based approaches in FuseTS. I didn't check if it's really the best option for this one though...

**Comment by jdries** [comment]
An example of someone trying to do lowess on xarray, resorted to using numba and numpy 'apply_along_axis':
https://gist.github.com/serazing/7dda94af17cf313e9ee019f12a1b093e

**Comment by HansVRP** [comment]
@jdries @soxofaan  are you happy with the changes made? If so I can give it one last review and merge

**Comment by jdries** [comment]
looks a lot better already
for the plot at the end: I had trouble comparing the curves. Maybe one option is to just have one plot, but showing the filled values in a different color? (Perhaps this can be achieve by simply plotting one graph on top of the other?)

**Comment by Pratichhya** [comment]
updated the plot 😃

**Comment by soxofaan** [comment]
`{job.describe()['costs']}`  
is there a particular reason to put the result in curly brackets?

About the plots: you seem to be doing quite some numpy hacks (e.g. `[1:]`, reshape) and there is hardcoding of the x label `Day since 2021-04-01`, which will be wrong if people start playing with the temporal extent. 
Can't this be simplified and generalized by sticking to basic Xarray operations?

**Comment by Pratichhya** [comment]
@HansVRP, I believe it is ready 😄. Please let me know if additional changes might be required

**Comment by HansVRP** [comment]
Hi Pratichhya, I am still not fully convinced on the notebook's name, InterpolateMissingData would be more on target

**Review by HansVRP — APPROVED** [review]

**Comment by VictorVerhaert** [comment]
Small comments:
- before starting the udf, I would already download the observed No2 before going over the udf as it might be confusing what data cube you are executing when
- I would show the cost of the filled job to showcase it is cheap

Lastly the readme of the python examples doesn't compile correctly for me. I would also add "applying UDF along the time dimension" to the demonstrates column

**Pull request merged**
