### PR TITLE
Forest Fire Mapping using Sentinel 2

### PR DESCRIPTION
**Pull request by Pratichhya**
In this notebook, we showcase the process up to the calculation of the difference of NDVI for pre and post-fire data using sentinel-2 discussed in the [paper](https://www.mdpi.com/2072-4292/12/13/2162#).

Furthermore, we also tried the NBR-based approach, which was mentioned in the paper but not implemented.

The PR is migrated from https://github.com/eu-cdse/notebook-samples/pull/43

### CODE REVIEW

**Review by jdries — CHANGES_REQUESTED** [review]
There's basic spelling errors/typos in the section after 'For that:'.
Best to try and do the editing in a tool that has a spell checker.

**Comment by Pratichhya** [comment]
> There's basic spelling errors/typos in the section after 'For that:'. Best to try and do the editing in a tool that has a spell checker.

Sorry about the stupid mistakes; actually, I was using Grammarly, but it seems like I misplaced the accepted corrections. They are corrected now; please let me know if I missed more of them.

**Comment by Pratichhya** [comment]
@jdries do you have any additional suggestion?

**Comment by jdries** [comment]
please use max_cloud_cover=90 in load_collection, we consistently want to recommend that
are you sure we still need resample_cube_spatial before doing mask? Does it give issues if not done?

**Comment by Pratichhya** [comment]
> please use max_cloud_cover=90 in load_collection, we consistently want to recommend that are you sure we still need resample_cube_spatial before doing mask? Does it give issues if not done?
 
Updated as suggested, and no, it doesn't give any issue when `resample_cube_spatial` is removed.

**Comment by Pratichhya** [comment]
@jdries, if it's ok, could you please approve this PR to as the first version(for a stable link)?

**Review by jdries — APPROVED** [review]

**Pull request merged**
