### PR TITLE
radar vegetation index

### PR DESCRIPTION
**Pull request by Pratichhya**
In this notebook, we want to study the health condition of vegetation using radar. Thus, we will use the Sentinel-1 GRD collection available within the Copernicus Data Space Ecosystem. The Radar Vegetation Index (RVI) is a measure used in remote sensing and agriculture to assess the health and condition of vegetation using radar data.

General example of openEO, thus migrated this notebook to this repo rather than cdse-specific(eu-cdse/notebook-samples#47)

### CODE REVIEW

**Comment by Pratichhya** [comment]
@soxofaan, I apologize for too many PRs closed and opened for this simple use case. I wasn't sure what was causing the action failure, tried several. So far it looks good here.

**Comment by soxofaan** [comment]
no problem

the LaTeX formula is a bit small to read properly , can you use display mode instead of inline mode? e.g. see https://www.learnlatex.org/en/lesson-10

> from openeo.processes import sqrt

I don't think this `sqrt` import is used, right?

> rvi = (4 * (s1.band("VH"))) / (s1.band("VV") + s1.band("VH"))

I think you can eliminate a couple of parentheses here

In the plots: you start talking about NDVI which makes no sense. You also use mean, max and median in the plot titles, but the three plots are from different time stamps.
I would also use a lower dpi value than 300 as this makes the font size quite large, usually 90 is enough for screen display.

In the time series plot you use figsize(18,6) and dpi=200, which creates a huge plot image (3000px wide) unnecessarily. Note that this weighs hevily on notebook and repo size.
I think you should stick to 90 dpi by default and keep figsize reasonably small.

about spectral indices: you should mention that this is an extra feature of the openeo python client, now it looks like it is something from the openEO ecosystem as a whole, which is not true.

**Comment by Pratichhya** [comment]
> from openeo.processes import sqrt

removed

> rvi = (4 * (s1.band("VH"))) / (s1.band("VV") + s1.band("VH"))

 modified

> I think you can eliminate a couple of parentheses here

eliminated 
 
> In the plots: you start talking about NDVI which makes no sense. You also use mean, max and median in the plot titles, but the three plots are from different time stamps. I would also use a lower dpi value than 300 as this makes the font size quite large, usually 90 is enough for screen display.
> In the time series plot you use figsize(18,6) and dpi=200, which creates a huge plot image (3000px wide) unnecessarily. Note that this weighs hevily on notebook and repo size. I think you should stick to 90 dpi by default and keep figsize reasonably small.

Sticked with 90dpi

> about spectral indices: you should mention that this is an extra feature of the openeo python client, now it looks like it is something from the openEO ecosystem as a whole, which is not true.

Updated the sentence

**Comment by soxofaan** [comment]
> `\sigma^0{ }_{V H}}`
is that `{ }` before the `_` intentional? I think the math will look cleaner if you just use `\sigma^0_{V H}}`

> Temporal mean of  RVI ..... Temporal max of RVI ... Temporal median of RVI

Where does this mean/max/median come from? this is just a timeseries, right?

> Alternatively, you can use [compute_indices](https://open-eo.github.io/openeo-python-client/cookbook/spectral_indices.html#module-openeo.extra.spectral_indices) process for the computation of a wide range of indices.
> Moreover, You can simplify your process by using the [Awesome Spectral Indices](https://awesome-ee-spectral-indices.readthedocs.io/en/latest/) package to calculate several spectral indices.
> ...
> ### Let's plot the result
> Similarly, you can calculate more indices, as done above, without having to deal with the formulas.
> please note that this API is experimental and may undergo changes. Furthermore, there might be cases where it is not supported for certain collections when executed directly in the openEO web editor.

All this text feels a quite chaotic (e.g. the paragraph after "Let's plot the results" has nothing to do with plotting).
Proposal:

> The openEO Python client has a [spectral indices feature](https://open-eo.github.io/openeo-python-client/cookbook/spectral_indices.html) to simplify building process graphs with indices like RVI. It builds on the  [Awesome Spectral Indices](https://awesome-ee-spectral-indices.readthedocs.io/en/latest/) project and allows specifying indices through their name instead of having to deal with formulas. 
> For example, with the `compute_indices` helper you just have to specify "DpRVIVV" (Dual-Polarized Radar Vegetation Index VV) as follows:
> ...
>

**Comment by Pratichhya** [comment]
> Where does this mean/max/median come from? this is just a timeseries, right?

I am sorry maybe, I am confusing you, but there in the image, I simply wanted to show the mean, max, median value of a pixel over the selected temporal time. 

I included a sentence before the plot to avoid the confusion. If you think it is still better to remove the plot, I can make changes as you recommend.

**Comment by soxofaan** [comment]
ah ok I see now.

The max plot, completely polluted by clouds I guess, is in any case not interesting so I would not show it. Showing both mean and median is also not very interesting here, so  I would just stick to temporal median (or mean)

**Comment by Pratichhya** [comment]
> The max plot, completely polluted by clouds I guess, is in any case not interesting so I would not show it. Showing both mean and median is also not very interesting here, so I would just stick to temporal median (or mean)

Ahh ok sure, I updated the plot for mean only.

**Review by soxofaan — APPROVED** [review]

**Comment by Pratichhya** [comment]
@soxofaan, thank you for all the guidance. Also, could you please help me in merging this? I don't have the authorisation for this repo

**Pull request merged**
